version: '3.7'

networks:
  default:
    name: hypestock-net

services:
  hypestock-server:
    build:
      context: .
      dockerfile: Dockerfile.develop
    restart: 'no'
    volumes:
    - .:/app
