version: '3.7'

networks:
  default:
    name: hypestock-net

services:
  hypestock-mysql:
    image: mysql:5.7
    container_name: hypestock-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - '3306:3306'
    volumes:
      - ./system/mysql:/var/lib/mysql

  hypestock-server:
    build: .
    container_name: hypestock-server
    restart: always
    environment:
      - WAIT_HOSTS=${MYSQL_HOST}:${MYSQL_PORT}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - JWT_TOKEN_SECRET=${JWT_TOKEN_SECRET}
    ports:
      - '8000:8000'
